### ISSUE TITLE
Optimize MiddlewareFactory performance

### ISSUE THREAD

**Issue by samdark** [yiisoft/middleware-dispatcher#74]
In https://github.com/yiisoft/middleware-dispatcher/blob/master/src/MiddlewareFactory.php#L161 reflection is used on each call to `handle()` of the middleware. Reflection could be cached.

**Comment by vjik** [comment]
Here also: https://github.com/yiisoft/middleware-dispatcher/blob/master/src/MiddlewareFactory.php#L219

**Comment by vjik** [comment]
Closed by #75
